name: ClimateDiffuse
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - xarray
  - tensorboard
  - netcdf4
  - cartopy
  - matplotlib
  - scipy
  - jupyter
  - tqdm
